name: "French'Encas"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2843
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f5fa'
    - '#d7c8b5'
    - '#4c3734'
    - '#b06b41'
    - '#d89b6f'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
